#!/usr/bin/env python

def get_column_names(table):
    return tables2[table]

tables2 = dict([
                   
('variant_impacts', ['variant_id',
                'anno_id',
                'gene',
                'transcript',
                'is_exonic',
                'is_coding',
                'is_lof',
                'exon',
                'codon_change',
                'aa_change',
                'aa_length',
                'biotype',
                'impact',
                'impact_so',
                'impact_severity',
                'polyphen_pred',
                'polyphen_score',
                'sift_pred',
                'sift_score']),

('gene_detailed', ['uid',
                'chrom',
                'gene',
                'is_hgnc',
                'ensembl_gene_id',
                'transcript',
                'biotype',
                'transcript_status',
                'ccds_id',
                'hgnc_id',
                'entrez_id',
                'cds_length',
                'protein_length',
                'transcript_start',
                'transcript_end',
                'strand',
                'synonym',
                'rvis_pct',
                'mam_phenotype_id']),

('gene_summary', ['uid',
                'chrom',
                'gene',
                'is_hgnc',
                'ensembl_gene_id',
                'hgnc_id',
                'transcript_min_start',
                'transcript_max_end',
                'strand',
                'synonym',
                'rvis_pct',
                'mam_phenotype_id',
                'in_cosmic_census']),

('vcf_header',  ['vcf_header']),

('version', ['version']),
 
('resources',  ['name',
             'resource']),

('variants', ['chrom',
            'start',
            '\"end\"',
            'vcf_id',
            'variant_id',
            'anno_id',
            'ref',
            'alt',
            'qual',
            'filter',
            'type',
            'sub_type',
            'call_rate',
            'in_dbsnp',
            'rs_ids',
            'sv_cipos_start_left',
            'sv_cipos_end_left',
            'sv_cipos_start_right',
            'sv_cipos_end_right',
            'sv_length',
            'sv_is_precise',
            'sv_tool',
            'sv_evidence_type',
            'sv_event_id',
            'sv_mate_id',
            'sv_strand',
            'in_omim',
            'clinvar_sig',
            'clinvar_disease_name',
            'clinvar_dbsource',
            'clinvar_dbsource_id',
            'clinvar_origin',
            'clinvar_dsdb',
            'clinvar_dsdbid',
            'clinvar_disease_acc',
            'clinvar_in_locus_spec_db',
            'clinvar_on_diag_assay',
            'clinvar_causal_allele',
            'pfam_domain',
            'cyto_band',
            'rmsk',
            'in_cpg_island',
            'in_segdup',
            'is_conserved',
            'gerp_bp_score',
            'gerp_element_pval',
            'num_hom_ref',
            'num_het',
            'num_hom_alt',
            'num_unknown',
            'aaf',
            'hwe',
            'inbreeding_coeff',
            'pi',
            'recomb_rate',
            'gene',
            'transcript',
            'is_exonic',
            'is_coding',
            'is_lof',
            'exon',
            'codon_change',
            'aa_change',
            'aa_length',
            'biotype',
            'impact',
            'impact_so',
            'impact_severity',
            'polyphen_pred',
            'polyphen_score',
            'sift_pred',
            'sift_score',
            'anc_allele',
            'rms_bq',
            'cigar',
            'depth',
            'strand_bias',
            'rms_map_qual',
            'in_hom_run',
            'num_mapq_zero',
            'num_alleles',
            'num_reads_w_dels',
            'haplotype_score',
            'qual_depth',
            'allele_count',
            'allele_bal',
            'in_hm2',
            'in_hm3',
            'is_somatic',
            'somatic_score',
            'in_esp',
            'aaf_esp_ea',
            'aaf_esp_aa',
            'aaf_esp_all',
            'exome_chip',
            'in_1kg',
            'aaf_1kg_amr',
            'aaf_1kg_eas',
            'aaf_1kg_sas',
            'aaf_1kg_afr',
            'aaf_1kg_eur',
            'aaf_1kg_all',
            'grc',
            'gms_illumina',
            'gms_solid',
            'gms_iontorrent',
            'in_cse',
            'encode_tfbs',
            'encode_dnaseI_cell_count',
            'encode_dnaseI_cell_list',
            'encode_consensus_gm12878',
            'encode_consensus_h1hesc',
            'encode_consensus_helas3',
            'encode_consensus_hepg2',
            'encode_consensus_huvec',
            'encode_consensus_k562',
            'vista_enhancers',
            'cosmic_ids',
            'info',
            'cadd_raw',
            'cadd_scaled',
            'fitcons',
            'in_exac',
            'aaf_exac_all',
            'aaf_adj_exac_all',
            'aaf_adj_exac_afr',
            'aaf_adj_exac_amr',
            'aaf_adj_exac_eas',
            'aaf_adj_exac_fin',
            'aaf_adj_exac_nfe',
            'aaf_adj_exac_oth',
            'aaf_adj_exac_sas'])])    
 
tables = dict([
                   
('variant_impacts', [('variant_id', 'int'),
                ('anno_id', 'int'),
                ('gene', 'text'),
                ('transcript', 'text'),
                ('is_exonic', 'int'),
                ('is_coding', 'int'),
                ('is_lof', 'int'),
                ('exon', 'text'),
                ('codon_change', 'text'),
                ('aa_change', 'text'),
                ('aa_length', 'text'),
                ('biotype', 'text'),
                ('impact', 'text'),
                ('impact_so', 'text'),
                ('impact_severity', 'text'),
                ('polyphen_pred', 'text'),
                ('polyphen_score', 'float'),
                ('sift_pred', 'text'),
                ('sift_score', 'float')]),

('gene_detailed', [('uid', 'int'),
                ('chrom', 'text'),
                ('gene', 'text'),
                ('is_hgnc', 'int'),
                ('ensembl_gene_id', 'text'),
                ('transcript', 'text'),
                ('biotype', 'text'),
                ('transcript_status', 'text'),
                ('ccds_id', 'text'),
                ('hgnc_id', 'text'),
                ('entrez_id', 'text'),
                ('cds_length', 'text'),
                ('protein_length', 'text'),
                ('transcript_start', 'text'),
                ('transcript_end', 'text'),
                ('strand', 'text'),
                ('synonym', 'text'),
                ('rvis_pct', 'float'),
                ('mam_phenotype_id', 'text')]),

('gene_summary', [('uid', 'int'),
                ('chrom', 'text'),
                ('gene', 'text'),
                ('is_hgnc', 'int'),
                ('ensembl_gene_id', 'text'),
                ('hgnc_id', 'text'),
                ('transcript_min_start', 'text'),
                ('transcript_max_end', 'text'),
                ('strand', 'text'),
                ('synonym', 'text'),
                ('rvis_pct', 'float'),
                ('mam_phenotype_id', 'text'),
                ('in_cosmic_census', 'boolean')]),

('vcf_header',  [('vcf_header', 'text')]),

('version', [('version', 'text')]),
 
('resources',  [('name', 'text'),
             ('resource', 'text')]),

('variants', [('chrom', 'text'),
            ('start', 'int'),
            ('end', 'int'),
            ('vcf_id', 'text'),
            ('variant_id', 'int'),
            ('anno_id', 'int'),
            ('ref', 'text'),
            ('alt', 'text'),
            ('qual', 'float'),
            ('filter', 'text'),
            ('type', 'text'),
            ('sub_type', 'text'),
            ('call_rate', 'float'),
            ('in_dbsnp', 'int'),
            ('rs_ids', 'text'),
            ('sv_cipos_start_left', 'int'),
            ('sv_cipos_end_left', 'int'),
            ('sv_cipos_start_right', 'int'),
            ('sv_cipos_end_right', 'int'),
            ('sv_length', 'int'),
            ('sv_is_precise', 'boolean'),
            ('sv_tool', 'text'),
            ('sv_evidence_type', 'text'),
            ('sv_event_id', 'text'),
            ('sv_mate_id', 'text'),
            ('sv_strand', 'text'),
            ('in_omim', 'int'),
            ('clinvar_sig', 'text'),
            ('clinvar_disease_name', 'text'),
            ('clinvar_dbsource', 'text'),
            ('clinvar_dbsource_id', 'text'),
            ('clinvar_origin', 'text'),
            ('clinvar_dsdb', 'text'),
            ('clinvar_dsdbid', 'text'),
            ('clinvar_disease_acc', 'text'),
            ('clinvar_in_locus_spec_db', 'int'),
            ('clinvar_on_diag_assay', 'int'),
            ('clinvar_causal_allele', 'text'),
            ('pfam_domain', 'text'),
            ('cyto_band', 'text'),
            ('rmsk', 'text'),
            ('in_cpg_island', 'boolean'),
            ('in_segdup', 'boolean'),
            ('is_conserved', 'boolean'),
            ('gerp_bp_score', 'float'),
            ('gerp_element_pval', 'float'),
            ('num_hom_ref', 'int'),
            ('num_het', 'int'),
            ('num_hom_alt', 'int'),
            ('num_unknown', 'int'),
            ('aaf', 'decimal'),
            ('hwe', 'decimal'),
            ('inbreeding_coeff', 'float'),
            ('pi', 'float'),
            ('recomb_rate', 'float'),
            ('gene', 'text'),
            ('transcript', 'text'),
            ('is_exonic', 'int'),
            ('is_coding', 'int'),
            ('is_lof', 'int'),
            ('exon', 'text'),
            ('codon_change', 'text'),
            ('aa_change', 'text'),
            ('aa_length', 'text'),
            ('biotype', 'text'),
            ('impact', 'text'),
            ('impact_so', 'text'),
            ('impact_severity', 'text'),
            ('polyphen_pred', 'text'),
            ('polyphen_score', 'float'),
            ('sift_pred', 'text'),
            ('sift_score', 'float'),
            ('anc_allele', 'text'),
            ('rms_bq', 'float'),
            ('cigar', 'text'),
            ('depth', 'int'),
            ('strand_bias', 'float'),
            ('rms_map_qual', 'float'),
            ('in_hom_run', 'int'),
            ('num_mapq_zero', 'int'),
            ('num_alleles', 'int'),
            ('num_reads_w_dels', 'float'),
            ('haplotype_score', 'float'),
            ('qual_depth', 'float'),
            ('allele_count', 'int'),
            ('allele_bal', 'float'),
            ('in_hm2', 'int'),
            ('in_hm3', 'int'),
            ('is_somatic', 'int'),
            ('somatic_score', 'float'),
            ('in_esp', 'boolean'),
            ('aaf_esp_ea', 'float'),
            ('aaf_esp_aa', 'float'),
            ('aaf_esp_all', 'float'),
            ('exome_chip', 'boolean'),
            ('in_1kg', 'boolean'),
            ('aaf_1kg_amr', 'float'),
            ('aaf_1kg_eas', 'float'),
            ('aaf_1kg_sas', 'float'),
            ('aaf_1kg_afr', 'float'),
            ('aaf_1kg_eur', 'float'),
            ('aaf_1kg_all', 'float'),
            ('grc', 'text'),
            ('gms_illumina', 'float'),
            ('gms_solid', 'float'),
            ('gms_iontorrent', 'float'),
            ('in_cse', 'boolean'),
            ('encode_tfbs', 'text'),
            ('encode_dnaseI_cell_count', 'int'),
            ('encode_dnaseI_cell_list', 'text'),
            ('encode_consensus_gm12878', 'text'),
            ('encode_consensus_h1hesc', 'text'),
            ('encode_consensus_helas3', 'text'),
            ('encode_consensus_hepg2', 'text'),
            ('encode_consensus_huvec', 'text'),
            ('encode_consensus_k562', 'text'),
            ('vista_enhancers', 'text'),
            ('cosmic_ids', 'text'),
            ('info', 'blob'),
            ('cadd_raw', 'float'),
            ('cadd_scaled', 'float'),
            ('fitcons', 'float'),
            ('in_exac', 'boolean'),
            ('aaf_exac_all', 'decimal'),
            ('aaf_adj_exac_all', 'decimal'),
            ('aaf_adj_exac_afr', 'decimal'),
            ('aaf_adj_exac_amr', 'decimal'),
            ('aaf_adj_exac_eas', 'decimal'),
            ('aaf_adj_exac_fin', 'decimal'),
            ('aaf_adj_exac_nfe', 'decimal'),
            ('aaf_adj_exac_oth', 'decimal'),
            ('aaf_adj_exac_sas', 'decimal')])])       
